### ISSUE TITLE
Allow getting raw image

### ISSUE THREAD

**Issue by UnsolvedCypher** [tdecker91/visualcube#1]
Firstly, thanks for taking the time to port this to TypeScript! It's much nicer than having to deal with PHP. I think it would be very convenient to be able to get just the SVG or PNG as a string rather than forcing it to be rendered in an HTML element. This would make this library more suited for usage in an API rather than only on the front-end.

**Comment by tdecker91** [comment]
Hey, sorry for such a late reply. 

That’s a great idea. Unfortunately it wasn’t originally made with that idea in mind and relies heavily on svg.js which just creates svg elements in a browser context. Even the png support is just a silly hack that converts svg elements to png in the browser. But I’m open to PRs :) 

If I’m not mistaken even the original php version output svg and used image magik to convert to different image formats. It’s just so convenient to let something else handle the actual drawing routines 😅

I’ve since been working on another project that aims to be more modular to support scenarios like this.  Potentially be able to run in an API context, or even react native. I ripped out the dependency on svg.js and allow for custom renderers. 

Stay tuned if you want to follow https://github.com/tdecker91/puzzle-visualizer

**Comment by tdecker91** [comment]
See https://github.com/tdecker91/puzzle-visualizer https://tdecker91.github.io/puzzle-gen/#/advanced?id=custom-renderers
