### ISSUE TITLE
Link generator

### ISSUE THREAD

**Issue by tarasovladislav** [tdecker91/visualcube#11]
Hi

Is it possible to do it the same as original? So you type the query and get an image directly (for png) (without rendering the html page) 

http://cube.rider.biz/visualcube.png?fmt=svg&size=150&pzl=2&alg=R2F2R2

**Comment by tdecker91** [comment]
Hey thanks for the interest in this project.

Unfortunately I do not think it would be possible to do this because the ‘svg.js’ library is used to render to svg using JavaScript. Plus it’s a little outside the scope of what this was built for. 

Original plan for this was to allow rendering cube images within single page apps without needing to run php

Even if this was run using server side JavaScript in node or something it would fail because svg.js requires a DOM. 

My other library supports this a little better, but again, not out of the box. See [here](https://github.com/tdecker91/puzzle-gen/issues/1)

the purpose of this project is to provide a library for rendering cubes, not necessarily the server support to provide host for cubing images.
