### ISSUE TITLE
Sometimes D-Face disappears

### ISSUE THREAD

**Issue by roudai** [tdecker91/visualcube#8]
D-Face disappears
{ "viewportRotations": [ [ Axis.X, 60 ], [ Axis.Y, 30 ], [ Axis.Z, 0 ] ] }
D-Face appears
{ "viewportRotations": [ [ Axis.X, 65 ], [ Axis.Y, 30 ], [ Axis.Z, 0 ] ] }

**Comment by tdecker91** [comment]
@roudai haha, not sure why I never noticed this before 😅. Looks like I had a small typo. This should be fixed in `v1.0.12`

By the way, if you're interested you should check out the successor to this library https://github.com/tdecker91/puzzle-gen
Hopefully it's a bit easier to use, and has more features.

**Comment by roudai** [comment]
Thank you for the quick response!
I have developed VisualCube Editor 2.0, an application to operate VisualCube TS with GUI.
[https://github.com/roudai/VisualCubeEditor2](https://github.com/roudai/VisualCubeEditor2)
VisualCube TS is very convenient for making this.
PuzzleGen is also very nice and I would like to make something using it.

**Comment by tdecker91** [comment]
Very nice 👍
